eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    #续约更新时间间隔
    lease-renewal-interval-in-seconds: 10
    #续约到期时间
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://clouddo-server:8761/eureka/
server:
  port: 8002
spring:
  application:
    name: clouddo-zuul
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000



