server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://clouddo-server:8761/eureka/
spring:
  application:
    name: clouddo-base
  datasource:
    url: jdbc:mysql://10.1.12.4:3306/clouddo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: P@ssw0rd`123
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true